### ISSUE TITLE
import caffe error

### ISSUE THREAD

**Issue by woshigcy** [yjxiong/temporal-segment-networks#158]
Hi,Thank you for your work first!
when i run the code like below, it makes some mistake, and i didn't how it happened , can you give me some suggestion about this ? Thank you!
 python2 tools/eval_net.py ucf101 1 flow /home/zhangtian/UCFOUT/ models/ucf101/tsn_bn_inception_flow_deploy.prototxt models/ucf101_split1_tsn_flow_bn_inception_iter_18000.caffemodel --num_worker 3 --save_scores score.txt
Namespace(caffe_path='./lib/caffe-action/', dataset='ucf101', flow_x_prefix='flow_x_', flow_y_prefix='flow_y_', frame_path='/home/zhangtian/UCFOUT/', gpus=None, modality='flow', net_proto='models/ucf101/tsn_bn_inception_flow_deploy.prototxt', net_weights='models/ucf101_split1_tsn_flow_bn_inception_iter_18000.caffemodel', num_frame_per_video=25, num_worker=3, rgb_prefix='img_', save_scores='score.txt', split=1)
Traceback (most recent call last):
  File "tools/eval_net.py", line 38, in <module>
    from pyActionRecog.action_caffe import CaffeNet
  File "/home/zhangtian/temporal-segment-networks/pyActionRecog/action_caffe.py", line 4, in <module>
    import caffe
  File "/home/zhangtian/temporal-segment-networks/lib/caffe-action/python/caffe/__init__.py", line 1, in <module>
    from .pycaffe import Net, SGDSolver
  File "/home/zhangtian/temporal-segment-networks/lib/caffe-action/python/caffe/pycaffe.py", line 15, in <module>
    import caffe.io
  File "/home/zhangtian/temporal-segment-networks/lib/caffe-action/python/caffe/io.py", line 8, in <module>
    from caffe.proto import caffe_pb2
  File "/home/zhangtian/temporal-segment-networks/lib/caffe-action/python/caffe/proto/caffe_pb2.py", line 797, in <module>
    options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001')), file=DESCRIPTOR),
TypeError: __new__() got an unexpected keyword argument 'file'

**Comment by woshigcy** [comment]
This is caused by version of protobuf
