### ISSUE TITLE
error in running the eval_net.py

### ISSUE THREAD

**Issue by humengdoudou** [yjxiong/temporal-segment-networks#167]
I extracted the rbg images and the flow_x、flow_y data rightly，and successfully run the eval_net.py.
But the program interrupt at the middle of the files：

video v_HammerThrow_g13_c07 done
video v_Kayaking_g11_c04 done
video v_HammerThrow_g14_c01 done
video v_Kayaking_g11_c05 done
video v_HammerThrow_g14_c02 done
video v_Kayaking_g11_c06 done
video v_HammerThrow_g14_c03 done
video v_Kayaking_g11_c07 done
video v_HammerThrow_g14_c04 done
video v_Kayaking_g12_c01 done
video v_HammerThrow_g14_c05 done
video v_Kayaking_g12_c02 done
video v_HammerThrow_g14_c06 done
Traceback (most recent call last):
  File "tools/eval_net.py", line 117, in <module>
    video_scores = pool.map(eval_video, eval_video_list)
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 251, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 567, in get
    raise self._value
KeyError: 'v_HandStandPushups_g08_c01'

this means I run the code successfully， it is common in interruptting at the first file：KeyError: 'v_ApplyEyeMakeup_g01_c01'， but mine interrupt at v_HandStandPushups_g08_c01.

i re-extract the rbg images and the flow_x、flow_y data in v_HandStandPushups_g08_c01，but it also goes wrong.
can you help me figure out this problem?

**Comment by humengdoudou** [comment]
i find the problem，it is the name unmatch problem in ucf101 and the tsn's data/ucf101_splits，in ucf101，the video and the image name are HandstandPushups，but in ucf101_splits/testlist01.txt，the name is HandStandPushups，the difference are the ‘stand’ and the ‘Stand’， so i fixed the HandStandPushups to HandstandPushups in testlist01.txt， and it works ok now；
