### ISSUE TITLE
No registered converter was able to extract a C++ pointer to type char from this Python object of type bytes

### ISSUE THREAD

**Issue by baiqilin1991** [yjxiong/temporal-segment-networks#282]
when I run `dense_flow/tools/extract_flow.py`

Traceback (most recent call last):
  File "extract_flow.py", line 71, in <module>
    flow_frames = f.extract_flow(frame_list)
  File "extract_flow.py", line 23, in extract_flow
    rst = self._et.extract_flow([x.tostring() for x in frame_list], frame_size[1], frame_size[0])
TypeError: No registered converter was able to extract a C++ pointer to type char from this Python object of type bytes

can any one help me?

**Comment by baiqilin1991** [comment]
@yjxiong
